# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
    container: maven:3.9.2-amazoncorretto-17
    defaults:
      run:
        working-directory: ./app
    # The type of runner that the job will run on
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE

      # Runs a single command using the runners shell
      - name: Generate JAR
        run: ls #cd source-app && mvn -f /github/workspace/source-app/pom.xml clean package

#       - name: Archive code coverage results
#         uses: actions/upload-artifact@v3
#         with:
#           name: jar-artifact
#           path: /github/workspace/source-app/target/social-network-0.0.1-SNAPSHOT.jar

