# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
    container: amazoncorretto:17-alpine3.17
    # The type of runner that the job will run on
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Generate JAR
        run: ls -la
        #mvn -f /github/workspace/pom.xml clean package

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifact
          path: /github/workspace/target/social-network-0.0.1-SNAPSHOT.jar

