apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata: 
  name: local-admin
rules:
- apiGroups: 
  - '*' 
  resources: 
  - '*' 
  verbs: 
    - '*'
- nonResourceURLs: 
  - '*'
  verbs: 
  - '*'